import React, { useState, useEffect } from "react";
import AdminSidebar from "../components/AdminSidebar";
import GenerateReportCard from "../components/usage/GenerateReportCard";
import GeneratedReportsTable from "../components/usage/GeneratedReportsTable";
import { supabase } from "../../supabaseClient";
import jsPDF from "jspdf";

function Usage() {
  const [isOpen, setIsOpen] = useState(true);
  const [reports, setReports] = useState([]);
  const [loading, setLoading] = useState(true);

  useEffect(() => {
    fetchReports();
  }, []);

  async function fetchReports() {
    setLoading(true);
    const { data, error } = await supabase
      .from("report")
      .select("*")
      .order("created_at", { ascending: false });

    if (error) {
      console.error("Error fetching reports:", error.message);
      alert("Failed to fetch reports.");
    } else {
      setReports(
        data.map((r) => ({
          name: r.name,
          type: r.type,
          dateRange: r.date_range,
          generatedBy: r.generated_by,
          file_path: r.file_path,
        }))
      );
    }
    setLoading(false);
  }

  async function handleGenerate({ type, dateRange, year, specificUser }) {
    if (!type || !dateRange) {
      alert("Please select a report type and date range before generating.");
      return;
    }

    const currentDate = new Date().toISOString().split("T")[0];
    const generatedBy = specificUser ? `Admin for ${specificUser}` : "Admin User";
    const name = `${type} - ${dateRange}${year ? " " + year : ""}`.trim();

    try {
      // ✅ Use EXPLICIT relationship alias to resolve PGRST201
     const { data: requests, error } = await supabase
  .from("print_request")
  .select(`
    request_id,
    student_id,
    file_name,
    paper_size,
    num_pages,
    num_copies,
    print_type,
    datetime_requested,
    print_transaction:print_transaction!print_transaction_request_id_fkey (
      tokens_deducted,
      issued_by,
      status
    )
  `);


      if (error) throw new Error(`Database fetch failed: ${error.message}`);
      if (!requests || requests.length === 0) {
        alert("No print requests found for the selected criteria.");
        return;
      }

      // ✅ Compute metrics
      const totalRequests = requests.length;
      const totalPages = requests.reduce(
        (sum, r) => sum + (r.num_pages || 0) * (r.num_copies || 1),
        0
      );
      const totalTokens = requests.reduce(
        (sum, r) => sum + (r.print_transaction?.tokens_deducted || 0),
        0
      );
      const avgTokensPerPage =
        totalPages > 0 ? (totalTokens / totalPages).toFixed(2) : "0.00";

      const colorPrints = requests.filter((r) => r.print_type === "Color").length;
      const grayscalePrints = requests.filter((r) => r.print_type === "Grayscale").length;

      const paperSizeStats = {};
      const statusCounts = {};
      const tokensPerUser = {};
      const issuedByCounts = {};
      const pagesOverTime = {};

      requests.forEach((r) => {
        const size = r.paper_size || "Unknown";
        paperSizeStats[size] = (paperSizeStats[size] || 0) + 1;

        const status = r.print_transaction?.status || "N/A";
        statusCounts[status] = (statusCounts[status] || 0) + 1;

        const user = r.student_id;
        const tokens = r.print_transaction?.tokens_deducted || 0;
        tokensPerUser[user] = (tokensPerUser[user] || 0) + tokens;

        const staff = r.print_transaction?.issued_by || "Unassigned";
        issuedByCounts[staff] = (issuedByCounts[staff] || 0) + 1;

        const date = new Date(r.datetime_requested).toISOString().split("T")[0];
        const pages = (r.num_pages || 0) * (r.num_copies || 1);
        pagesOverTime[date] = (pagesOverTime[date] || 0) + pages;
      });

      // ✅ Generate clean, well-formatted PDF
      const doc = new jsPDF({ unit: "mm", format: "a4" });
      let y = 15;

      const addLine = (text, indent = 0, spacing = 6) => {
        doc.text(`${" ".repeat(indent)}${text}`, 10 + indent, y);
        y += spacing;
        if (y > 270) {
          doc.addPage();
          y = 20;
        }
      };

      doc.setFont("helvetica", "bold");
      doc.setFontSize(16);
      addLine("Usage Report Summary");
      doc.setFont("helvetica", "normal");
      doc.setFontSize(12);
      y += 4;

      addLine(`Report Type: ${type}`);
      addLine(`Date Range: ${dateRange}`);
      if (year) addLine(`Year: ${year}`);
      addLine(`Generated By: ${generatedBy}`);
      addLine(`Generated On: ${currentDate}`);
      y += 6;

      doc.setFont("helvetica", "bold");
      addLine("Summary Metrics:");
      doc.setFont("helvetica", "normal");
      addLine(`Total Requests: ${totalRequests}`, 4);
      addLine(`Total Pages Printed: ${totalPages}`, 4);
      addLine(`Total Tokens Spent: ${totalTokens}`, 4);
      addLine(`Average Tokens per Page: ${avgTokensPerPage}`, 4);
      y += 6;

      doc.setFont("helvetica", "bold");
      addLine("Requests by Status:");
      doc.setFont("helvetica", "normal");
      Object.entries(statusCounts).forEach(([s, c]) => addLine(`- ${s}: ${c}`, 4));
      y += 6;

      doc.setFont("helvetica", "bold");
      addLine("Issued By Breakdown:");
      doc.setFont("helvetica", "normal");
      Object.entries(issuedByCounts).forEach(([s, c]) => addLine(`- ${s}: ${c}`, 4));
      y += 6;

      doc.setFont("helvetica", "bold");
      addLine("Color vs Grayscale:");
      doc.setFont("helvetica", "normal");
      addLine(`- Color: ${colorPrints}`, 4);
      addLine(`- Grayscale: ${grayscalePrints}`, 4);
      y += 6;

      doc.setFont("helvetica", "bold");
      addLine("Paper Sizes Used:");
      doc.setFont("helvetica", "normal");
      Object.entries(paperSizeStats).forEach(([s, c]) => addLine(`- ${s}: ${c}`, 4));
      y += 6;

      doc.setFont("helvetica", "bold");
      addLine("Tokens per User:");
      doc.setFont("helvetica", "normal");
      Object.entries(tokensPerUser).forEach(([s, c]) => addLine(`- ${s}: ${c}`, 4));
      y += 6;

      doc.setFont("helvetica", "bold");
      addLine("Pages Over Time:");
      doc.setFont("helvetica", "normal");
      Object.entries(pagesOverTime).forEach(([date, pages]) =>
        addLine(`- ${date}: ${pages} pages`, 4)
      );
      y += 10;

      doc.setFont("helvetica", "bold");
      addLine("Detailed Requests (first 25):");
      doc.setFont("helvetica", "normal");
      requests.slice(0, 25).forEach((r, idx) => {
        addLine(
          `${idx + 1}. ${r.file_name} | ${r.paper_size} | ${r.print_type} | ${r.num_pages}p x${r.num_copies}`,
          4
        );
      });

      // ✅ Upload PDF
      const pdfBlob = doc.output("blob");
      const filePath = `${Date.now()}_${name.replace(/\s+/g, "_")}.pdf`;
      const { error: uploadError } = await supabase.storage
        .from("reports")
        .upload(filePath, pdfBlob, { contentType: "application/pdf" });

      if (uploadError) throw new Error(`File upload failed: ${uploadError.message}`);

      // ✅ Save metadata
      const { error: insertError } = await supabase.from("report").insert([
        {
          name,
          type,
          date_range: `${dateRange}${year ? " " + year : ""}`,
          generated_by: generatedBy,
          created_at: currentDate,
          file_path: filePath,
        },
      ]);

      if (insertError) throw new Error(`Database insert failed: ${insertError.message}`);

      alert("✅ Report generated successfully!");
      fetchReports();
    } catch (err) {
      console.error("Error generating report:", err);
      alert(`❌ Report generation failed:\n${err.message}`);
    }
  }

  async function handleDelete(report) {
    if (!window.confirm(`Delete "${report.name}"?`)) return;

    const { error: dbError } = await supabase
      .from("report")
      .delete()
      .eq("name", report.name);

    if (dbError) {
      console.error("Error deleting report:", dbError.message);
      alert("Failed to delete report record.");
      return;
    }

    if (report.file_path) {
      const { error: storageError } = await supabase.storage
        .from("reports")
        .remove([report.file_path]);
      if (storageError) {
        console.error("Error deleting file:", storageError.message);
        alert("Deleted record but failed to remove file from storage.");
      }
    }

    fetchReports();
  }

  return (
    <div className="fade-in flex h-screen bg-sky-100 overflow-hidden">
      <AdminSidebar isOpen={isOpen} setIsOpen={setIsOpen} />
      <main className="flex-1 p-8 flex flex-col">
        <h1 className="text-3xl font-bold text-gray-900 mb-6">Usage & Activity</h1>

        <div className="bg-white rounded-3xl p-6 shadow-md flex-1 overflow-hidden flex flex-col space-y-8">
          <GenerateReportCard onGenerate={handleGenerate} />
          {loading ? (
            <p className="text-gray-500 text-center">Loading reports...</p>
          ) : (
            <GeneratedReportsTable reports={reports} onDelete={handleDelete} />
          )}
        </div>
      </main>
    </div>
  );
}

export default Usage;
