import React, { useState } from "react";
import AdminSidebar from "../components/AdminSidebar";
import logo from "../../assets/images/navink-logo.png";

function Usage() {
  const [isOpen, setIsOpen] = useState(true);

  // Mock data for generated reports
  const reports = [
    {
      name: "Weekly Report - Week 40",
      type: "Weekly Usage",
      dateRange: "2025-10-01 to 2025-10-07",
      generatedBy: "Admin User",
    },
    {
      name: "Daily Summary - Oct 6",
      type: "Daily Summary",
      dateRange: "2025-10-06",
      generatedBy: "System (Auto)",
    },
    {
      name: "First Semester 2025",
      type: "Semester Overview",
      dateRange: "2025-01-05 to 2025-05-30",
      generatedBy: "Admin User",
    },
  ];

  return (
    <div className="fade-in flex min-h-screen bg-sky-100">
      <AdminSidebar isOpen={isOpen} setIsOpen={setIsOpen} />

      {/* Main Content */}
      <main className="flex-1 p-8 flex flex-col">
        {/* Page Title */}
        <h1 className="text-3xl font-bold text-gray-900 mb-6">Usage & Activity</h1>

        {/* White Card */}
        <div className="bg-white rounded-3xl p-6 shadow-md flex-1 overflow-hidden flex flex-col space-y-8">
          {/* Generate New Report */}
          <div className="bg-white border border-gray-200 rounded-2xl p-6">
            <h2 className="text-lg font-semibold text-gray-700 mb-4">
              Generate New Report
            </h2>
            <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-4 mb-6">
              {/* Report Type */}
              <div>
                <label className="block text-sm font-medium text-gray-600 mb-1">
                  Report Type
                </label>
                <select className="w-full px-4 py-2 border rounded-lg text-sm focus:outline-none focus:ring-2 focus:ring-sky-300">
                  <option>Select type</option>
                  <option>Daily Summary</option>
                  <option>Weekly Usage</option>
                  <option>Monthly Overview</option>
                  <option>Semester Report</option>
                </select>
              </div>

              {/* Start Date */}
              <div>
                <label className="block text-sm font-medium text-gray-600 mb-1">
                  Start Date
                </label>
                <input
                  type="text"
                  placeholder="dd/mm/yyyy"
                  className="w-full px-4 py-2 border rounded-lg text-sm focus:outline-none focus:ring-2 focus:ring-sky-300"
                />
              </div>

              {/* End Date */}
              <div>
                <label className="block text-sm font-medium text-gray-600 mb-1">
                  End Date
                </label>
                <input
                  type="text"
                  placeholder="dd/mm/yyyy"
                  className="w-full px-4 py-2 border rounded-lg text-sm focus:outline-none focus:ring-2 focus:ring-sky-300"
                />
              </div>

              {/* Specific User */}
              <div>
                <label className="block text-sm font-medium text-gray-600 mb-1">
                  Specific User (Optional)
                </label>
                <input
                  type="text"
                  placeholder="Enter ID number"
                  className="w-full px-4 py-2 border rounded-lg text-sm focus:outline-none focus:ring-ouffsky-300"
                />
              </div>
            </div>

            {/* Generate Button */}
            <div className="flex justify-end">
              <button className="bg-sky-600 hover:bg-sky-700 text-white font-medium px-6 py-2.5 rounded-lg transition shadow-sm">
                Generate Report
              </button>
            </div>
          </div>

          {/* Generated Reports Table */}
          <div className="flex-1 flex flex-col">
            <h2 className="text-lg font-semibold text-gray-700 mb-4">
              Generated Reports
            </h2>

            <div className="flex-1 overflow-x-auto border border-gray-200 rounded-2xl">
              <table className="w-full text-sm text-left">
                <thead className="text-xs text-gray-500 uppercase bg-gray-50">
                  <tr>
                    <th className="px-4 py-3">Report Name</th>
                    <th className="px-4 py-3">Type</th>
                    <th className="px-4 py-3">Date Range</th>
                    <th className="px-4 py-3">Generated By</th>
                    <th className="px-4 py-3 text-center">Actions</th>
                  </tr>
                </thead>
                <tbody className="divide-y divide-gray-200">
                  {reports.map((report, idx) => (
                    <tr key={idx} className="hover:bg-gray-50 transition">
                      <td className="px-4 py-3 font-medium text-gray-900">
                        {report.name}
                      </td>
                      <td className="px-4 py-3 text-gray-700">{report.type}</td>
                      <td className="px-4 py-3 text-gray-700">{report.dateRange}</td>
                      <td className="px-4 py-3 text-gray-600">{report.generatedBy}</td>
                      <td className="px-4 py-3 text-center">
                        <div className="flex justify-center gap-4">
                          {/* Download */}
                          <button className="text-sky-600 hover:text-sky-700 transition">
                            <img
                              src={logo}
                              alt="Download"
                              className="w-5 h-5 object-contain"
                            />
                          </button>
                          {/* Delete */}
                          <button className="text-red-600 hover:text-red-700 transition">
                            <img
                              src={logo}
                              alt="Delete"
                              className="w-5 h-5 object-contain"
                            />
                          </button>
                        </div>
                      </td>
                    </tr>
                  ))}
                </tbody>
              </table>
            </div>

            {/* Pagination Footer */}
            <div className="mt-4 flex justify-center">
              <div className="flex gap-1">
                <button className="w-8 h-8 border rounded-md text-xs text-gray-600 hover:bg-gray-100 flex items-center justify-center">
                  1
                </button>
                <button className="w-8 h-8 border rounded-md text-xs text-gray-400 bg-gray-100">
                  2
                </button>
                <button className="w-8 h-8 border rounded-md text-xs text-gray-400 bg-gray-100">
                  3
                </button>
              </div>
            </div>
          </div>
        </div>
      </main>
    </div>
  );
}

export default Usage;