import React, { useState, useEffect } from "react";
import AdminSidebar from "../components/AdminSidebar";
import GenerateReportCard from "../components/usage/GenerateReportCard";
import GeneratedReportsTable from "../components/usage/GeneratedReportsTable";
import { supabase } from "../../supabaseClient";
import jsPDF from "jspdf";

function Usage() {
  const [isOpen, setIsOpen] = useState(true);
  const [reports, setReports] = useState([]);
  const [loading, setLoading] = useState(true);

  useEffect(() => {
    fetchReports();
  }, []);

  // ✅ Fetch reports from Supabase
  async function fetchReports() {
    setLoading(true);
    const { data, error } = await supabase
      .from("report")
      .select("*")
      .order("created_at", { ascending: false });

    if (error) {
      console.error("Error fetching reports:", error);
    } else {
      setReports(
        data.map((r) => ({
          name: r.name,
          type: r.type,
          dateRange: r.date_range,
          generatedBy: r.generated_by,
          file_path: r.file_path,
        }))
      );
    }
    setLoading(false);
  }

  // ✅ Generate and upload a report PDF
  async function handleGenerate({ type, dateRange, year, specificUser }) {
    if (!type || !dateRange) {
      alert("Please select a report type and date range before generating.");
      return;
    }

    const currentDate = new Date().toISOString().split("T")[0];
    const generatedBy = specificUser ? `Admin for ${specificUser}` : "Admin User";
    const name = `${type} - ${dateRange} ${year ? year : ""}`.trim();

    try {
      const reportData = {
        total_requests: 6,
        total_pages: 129,
        total_tokens: 129,
        unique_students: 4,
      };

      // 🧾 Create PDF
      const doc = new jsPDF();
      doc.text("Usage Report Summary", 10, 10);
      doc.text(`Report Type: ${type}`, 10, 20);
      doc.text(`Date Range: ${dateRange}`, 10, 30);
      doc.text(`Generated By: ${generatedBy}`, 10, 40);
      doc.text(`Generated On: ${currentDate}`, 10, 50);
      doc.text("Report Data:", 10, 70);
      doc.text(JSON.stringify(reportData, null, 2), 10, 80);

      const pdfBlob = doc.output("blob");

      // ✅ Upload to Supabase Storage
      const filePath = `${Date.now()}_${name.replace(/\s+/g, "_")}.pdf`;

      const { data: uploadData, error: uploadError } = await supabase.storage
        .from("reports")
        .upload(filePath, pdfBlob, { contentType: "application/pdf", upsert: false });

      if (uploadError) {
        console.error("Error uploading file:", uploadError);
        alert("Failed to upload report file.");
        return;
      }

      // ✅ Insert DB record
      const { error: insertError } = await supabase.from("report").insert([
        {
          name,
          type,
          date_range: `${dateRange} ${year ? year : ""}`,
          generated_by: generatedBy,
          created_at: currentDate,
          file_path: filePath,
        },
      ]);

      if (insertError) {
        console.error("DB insert error:", insertError);
        alert("Failed to save report in database.");
        return;
      }

      alert("Report generated successfully!");
      fetchReports();
    } catch (err) {
      console.error("Error generating report:", err);
      alert("Something went wrong. Check console for details.");
    }
  }

  // ✅ Delete report
  async function handleDelete(report) {
    if (!window.confirm(`Delete "${report.name}"?`)) return;

    const { error: dbError } = await supabase.from("report").delete().eq("name", report.name);
    if (dbError) {
      console.error("Error deleting report:", dbError);
      alert("Failed to delete report from database.");
      return;
    }

    if (report.file_path) {
      const { error: storageError } = await supabase.storage.from("reports").remove([report.file_path]);
      if (storageError) {
        console.error("Error deleting file:", storageError);
        alert("Deleted DB record but failed to remove file from storage.");
      }
    }

    fetchReports();
  }

  return (
    <div className="fade-in flex h-screen bg-sky-100 overflow-hidden">
      <AdminSidebar isOpen={isOpen} setIsOpen={setIsOpen} />

      <main className="flex-1 p-8 flex flex-col">
        <h1 className="text-3xl font-bold text-gray-900 mb-6">Usage & Activity</h1>

        <div className="bg-white rounded-3xl p-6 shadow-md flex-1 overflow-hidden flex flex-col space-y-8">
          <GenerateReportCard onGenerate={handleGenerate} />
          {loading ? (
            <p className="text-gray-500 text-center">Loading reports...</p>
          ) : (
            <GeneratedReportsTable reports={reports} onDelete={handleDelete} />
          )}
        </div>
      </main>
    </div>
  );
}

export default Usage;
