import React from 'react';
import fileDownloadIcon from '../../../assets/icons/file-download-icon.svg';
import trashIcon from '../../../assets/icons/trash-icon.svg';

function GeneratedReportsTable({ reports }) {
  return (
    <div className="flex-1 flex flex-col">
      <h2 className="text-lg font-semibold text-gray-700 mb-4">Generated Reports</h2>

      <div className="flex-1 overflow-x-auto border border-gray-200 rounded-2xl">
        <table className="w-full text-sm text-left">
          <thead className="text-xs text-gray-500 uppercase bg-gray-50">
            <tr>
              <th className="px-4 py-3">Report Name</th>
              <th className="px-4 py-3">Type</th>
              <th className="px-4 py-3">Date Range</th>
              <th className="px-4 py-3">Generated By</th>
              <th className="px-4 py-3 text-center">Actions</th>
            </tr>
          </thead>
          <tbody className="divide-y divide-gray-200">
            {reports.map((report, idx) => (
              <tr key={idx} className="hover:bg-gray-50 transition">
                <td className="px-4 py-3 font-medium text-gray-900">{report.name}</td>
                <td className="px-4 py-3 text-gray-700">{report.type}</td>
                <td className="px-4 py-3 text-gray-700">{report.dateRange}</td>
                <td className="px-4 py-3 text-gray-600">{report.generatedBy}</td>
                <td className="px-4 py-3 text-center">
                  <div className="flex justify-center gap-4">
                    {/* Download */}
                    <button className="text-sky-600 hover:text-sky-700 transition">
                      <img src={fileDownloadIcon} alt="Download" className="w-5 h-5 object-contain" />
                    </button>
                    {/* Delete */}
                    <button className="text-red-600 hover:text-red-700 transition">
                      <img src={trashIcon} alt="Delete" className="w-5 h-5 object-contain" />
                    </button>
                  </div>
                </td>
              </tr>
            ))}
          </tbody>
        </table>
      </div>

      {/* Pagination Footer */}
      <div className="mt-4 flex justify-center">
        <div className="flex gap-1">
          <button className="w-8 h-8 border rounded-md text-xs text-gray-600 hover:bg-gray-100 flex items-center justify-center">1</button>
          <button className="w-8 h-8 border rounded-md text-xs text-gray-400 bg-gray-100">2</button>
          <button className="w-8 h-8 border rounded-md text-xs text-gray-400 bg-gray-100">3</button>
        </div>
      </div>
    </div>
  );
}

export default GeneratedReportsTable;
