import React from "react";
import { supabase } from "../../../supabaseClient";
import fileDownloadIcon from "../../../assets/icons/file-download-icon.svg";
import trashIcon from "../../../assets/icons/trash-icon.svg";

function GeneratedReportsTable({ reports, onDelete }) {
  async function handleDownload(report) {
    if (!report.file_path) {
      alert("This report has no downloadable file.");
      return;
    }

    const { data, error } = await supabase.storage.from("reports").download(report.file_path);
    if (error) {
      console.error("Error downloading file:", error);
      alert("Failed to download file.");
      return;
    }

    const url = URL.createObjectURL(data);
    const a = document.createElement("a");
    a.href = url;
    a.download = `${report.name}.pdf`;
    document.body.appendChild(a);
    a.click();
    a.remove();
    URL.revokeObjectURL(url);
  }

  return (
    <div className="flex flex-col flex-1 bg-white rounded-3xl p-6 shadow-md">
      <h2 className="text-lg font-semibold text-gray-700 mb-4">Generated Reports</h2>

      {/* Desktop Table */}
      <div className="hidden md:block overflow-x-auto border border-gray-200 rounded-2xl shadow-sm">
        <table className="min-w-[720px] w-full table-auto text-sm text-left">
          <thead className="text-xs text-gray-500 uppercase bg-gray-50">
            <tr>
              <th className="px-4 py-3 whitespace-nowrap">Report Name</th>
              <th className="px-4 py-3 whitespace-nowrap">Type</th>
              <th className="px-4 py-3 whitespace-nowrap">Date Range</th>
              <th className="px-4 py-3 whitespace-nowrap">Generated By</th>
              <th className="px-4 py-3 text-center whitespace-nowrap">Actions</th>
            </tr>
          </thead>
          <tbody className="divide-y divide-gray-200">
            {reports.map((r, i) => (
              <tr key={i} className="hover:bg-gray-50 transition">
                <td className="px-4 py-3 font-medium text-gray-900 max-w-[200px]">
                  <div className="truncate" title={r.name}>{r.name}</div>
                </td>
                <td className="px-4 py-3 text-gray-700 max-w-[160px]">
                  <div className="truncate" title={r.type}>{r.type}</div>
                </td>
                <td className="px-4 py-3 text-gray-700 whitespace-nowrap max-w-[180px]">
                  <div className="truncate" title={r.dateRange}>{r.dateRange}</div>
                </td>
                <td className="px-4 py-3 text-gray-600 max-w-[160px]">
                  <div className="truncate" title={r.generatedBy}>{r.generatedBy}</div>
                </td>
                <td className="px-4 py-3 text-center">
                  <div className="flex justify-center gap-4">
                    <button onClick={() => handleDownload(r)} className="text-sky-600 hover:text-sky-700 transition">
                      <img src={fileDownloadIcon} alt="Download" className="w-5 h-5 object-contain" />
                    </button>
                    <button onClick={() => onDelete?.(r)} className="text-red-600 hover:text-red-700 transition">
                      <img src={trashIcon} alt="Delete" className="w-5 h-5 object-contain" />
                    </button>
                  </div>
                </td>
              </tr>
            ))}
          </tbody>
        </table>
      </div>

      {/* Mobile Card List */}
      <div className="md:hidden flex flex-col gap-4">
        {reports.map((r, i) => (
          <div key={i} className="bg-white rounded-2xl border border-gray-200 p-4 shadow-sm overflow-hidden">
            <div className="flex items-start justify-between mb-2">
              <div className="flex-1 pr-2">
                <h3 className="text-sm font-semibold text-gray-900 truncate mb-1" title={r.name}>
                  {r.name}
                </h3>
                <p className="text-xs text-gray-500 truncate" title={r.type}>{r.type}</p>
              </div>
            </div>
            <div className="text-sm text-gray-700 mb-1 truncate" title={r.dateRange}>
              <span className="font-medium">Date Range:</span> {r.dateRange}
            </div>
            <div className="text-sm text-gray-600 mb-3 truncate" title={r.generatedBy}>
              <span className="font-medium">Generated By:</span> {r.generatedBy}
            </div>
            <div className="flex gap-2">
              <button onClick={() => handleDownload(r)} className="flex-1 bg-sky-600 hover:bg-sky-700 text-white text-xs font-medium px-3 py-2 rounded-lg transition shadow-sm flex items-center justify-center gap-1">
                <img src={fileDownloadIcon} alt="Download" className="w-4 h-4 object-contain brightness-0 invert" />
                Download
              </button>
              <button onClick={() => onDelete?.(r)} className="flex-1 bg-red-600 hover:bg-red-700 text-white text-xs font-medium px-3 py-2 rounded-lg transition shadow-sm flex items-center justify-center gap-1">
                <img src={trashIcon} alt="Delete" className="w-4 h-4 object-contain brightness-0 invert" />
                Delete
              </button>
            </div>
          </div>
        ))}
      </div>

      {/* Pagination Footer */}
      <div className="mt-4 flex justify-center">
        <div className="flex gap-1">
          <button className="w-8 h-8 border rounded-md text-xs text-gray-600 hover:bg-gray-100 flex items-center justify-center">1</button>
          <button className="w-8 h-8 border rounded-md text-xs text-gray-400 bg-gray-100">2</button>
          <button className="w-8 h-8 border rounded-md text-xs text-gray-400 bg-gray-100">3</button>
        </div>
      </div>
    </div>
  );
}

export default GeneratedReportsTable;
