import React from "react";
import { supabase } from "../../../supabaseClient";
import fileDownloadIcon from "../../../assets/icons/file-download-icon.svg";
import trashIcon from "../../../assets/icons/trash-icon.svg";

function GeneratedReportsTable({ reports, onDelete }) {
  async function handleDownload(report) {
    if (!report.file_path) {
      alert("This report has no downloadable file.");
      return;
    }

    const { data, error } = await supabase.storage.from("reports").download(report.file_path);
    if (error) {
      console.error("Error downloading file:", error);
      alert("Failed to download file.");
      return;
    }

    const url = URL.createObjectURL(data);
    const a = document.createElement("a");
    a.href = url;
    a.download = `${report.name}.pdf`;
    document.body.appendChild(a);
    a.click();
    a.remove();
    URL.revokeObjectURL(url);
  }

  return (
    <div className="flex-1 flex flex-col">
      <h2 className="text-lg font-semibold text-gray-700 mb-4">Generated Reports</h2>

      <div className="flex-1 overflow-x-auto border border-gray-200 rounded-2xl">
        <table className="w-full text-sm text-left">
          <thead className="text-xs text-gray-500 uppercase bg-gray-50">
            <tr>
              <th className="px-4 py-3">Report Name</th>
              <th className="px-4 py-3">Type</th>
              <th className="px-4 py-3">Date Range</th>
              <th className="px-4 py-3">Generated By</th>
              <th className="px-4 py-3 text-center">Actions</th>
            </tr>
          </thead>
          <tbody className="divide-y divide-gray-200">
            {reports.map((r, i) => (
              <tr key={i} className="hover:bg-gray-50 transition">
                <td className="px-4 py-3 font-medium text-gray-900">{r.name}</td>
                <td className="px-4 py-3 text-gray-700">{r.type}</td>
                <td className="px-4 py-3 text-gray-700">{r.dateRange}</td>
                <td className="px-4 py-3 text-gray-600">{r.generatedBy}</td>
                <td className="px-4 py-3 text-center">
                  <div className="flex justify-center gap-4">
                    <button onClick={() => handleDownload(r)} className="text-sky-600 hover:text-sky-700 transition">
                      <img src={fileDownloadIcon} alt="Download" className="w-5 h-5 object-contain" />
                    </button>
                    <button onClick={() => onDelete?.(r)} className="text-red-600 hover:text-red-700 transition">
                      <img src={trashIcon} alt="Delete" className="w-5 h-5 object-contain" />
                    </button>
                  </div>
                </td>
              </tr>
            ))}
          </tbody>
        </table>
      </div>
    </div>
  );
}

export default GeneratedReportsTable;
